# Imagen base Node.js ligera para construir la app
FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /frontend

# Copiamos todo el código frontend
COPY . .

# Instalamos dependencias
RUN npm install

# Exponemos el puerto típico para dev server de Vite (puede ser otro)
EXPOSE 5173

# Comando por defecto para arrancar dev server (modo desarrollo)
CMD ["npm", "run", "dev"]
